# Generated by Django 4.0.6 on 2022-07-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Arcticles',
            new_name='Articles',
        ),
    ]
