# Generated by Django 4.0.6 on 2022-07-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_rename_arcticles_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='email',
        ),
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(null=True, upload_to='blog'),
        ),
    ]
